/// Kind of stable static tickers list
class TickersList {
  static Map<String, String> main = {
    '^GSPC': 'SP500',
    '^NDX': 'Nasdaq 100',
    'IWM': 'Russell 2000',
    'IWB': 'Russell 1000'
  };

  static Map<String, String> bonds = {
    '^IRX': 'USA 13 Week Bond yield',
    '^FVX': 'Treasury Yield 5 Years ',
    '^TNX': 'Treasury Yield 10 Years ',
    '^TYX': 'Treasury Yield 30 Years'
  };

  static Map<String, String> sectors = {
    'XLE': 'Energy',
    'XLF': 'Financials',
    'XLU': 'Utilities',
    'XLI': 'Industrial',
    'XLV': 'Healthcare',
    'XLY': 'Cons Discretionary',
    'XLP': 'Consumer Staples',
    'XLB': 'Materials',
    'REET': 'Real Estate',
    'XLC': 'Communication Services',
    'FCOM': 'Content'
  };

  static Map<String, String> countries = {
    'URTH': 'Whole World',
    'EWI': 'Italia',
    'RSX': 'Russia',
    'EWL': 'Switzerland',
    'EWU': 'UK',
    'EWI': 'Italy',
    'EWP': 'Spain',
    'EWA': 'Australia',
    'AFK': 'Whole Africa',
    'EGPT': 'Egypt',
    'EWA': 'South Africa',
    'MCHI': 'China',
    'FXI': 'China Large Cap',
    'CQQQ': 'China Tech',
    'THD': 'Thailand',
    'EWY': 'South Korea',
    'EWM': 'Malaysia',
    'EWS': 'Singapore',
    'DAX': 'Germany',
    'EWC': 'Canada',
    'EWZ': 'Brazil',
    'EWW': 'Mexico',
    'ARGT': 'Argentina',
    'EPU': 'Peru',
    'INDA': 'India',
    'INDY': 'India 50',
    'EIDO': 'Indonesia',
    'JPXN': 'Japan, Nikkei 400',
  };

  static Map<String, String> futures = {
    'ES=F': 'SP500',
    'NQ=F': 'Nasdaq',
    'GC=F': 'Gold',
    'SI=F': 'Silver',
    'CL=F': 'Oil',
    'HG=F': 'Copper',
    'NG=F': 'Natural Gas',
    'ZC=F': 'Corn',
    'ZS=F': 'Soybean',
    'CC=F': 'Cocoa',
    'KC=F': 'Coffee',
    'SB=F': 'Sugar',
    'ZB=F': 'Treasury Bond Futures'
  };

  static Map<String, String> sizes = {
    'VBR': 'Value small',
    'VOE': 'Value mid',
    'VTV': 'Value large',
    'VB': 'Core small',
    'VO': 'Core mid',
    'VV': 'Core large',
    'VBK': 'Growth small',
    'VOT': 'Growth mid',
    'VUG': 'Growth large'
  };

  static Map<String, String> cryptoCurrencies = {
    'BTC-USD': 'Bitcoin USD',
    'ETH-USD': 'Ethereum USD',
    'USDT-USD': 'Tether USD',
    'BNB-USD': 'Binance Coin USD',
    'USDC-USD': 'USD Coin USD',
    'HEX-USD': 'HEX USD',
    'XRP-USD': 'XRP USD',
    'SOL-USD': 'Solana USD',
    'LUNA1-USD': 'Terra USD',
    'ADA-USD': 'Cardano USD',
    'UST-USD': 'TerraUSD USD',
    'BUSD-USD': 'Binance USD USD',
    'DOGE-USD': 'Dogecoin USD',
    'AVAX-USD': 'Avalanche USD',
    'DOT-USD': 'Polkadot USD',
    'SHIB-USD': 'SHIBA INU USD',
    'WBTC-USD': 'Wrapped Bitcoin USD',
    'STETH-USD': 'Lido stETH USD',
    'MATIC-USD': 'Polygon USD',
    'DAI-USD': 'Dai USD',
    'NEAR-USD': 'NEAR Protocol USD',
    'WTRX-USD': 'Wrapped TRON USD',
    'TRX-USD': 'TRON USD',
    'CRO-USD': 'Crypto.com Coin USD',
    'LTC-USD': 'Litecoin USD',
    'BCH-USD': 'Bitcoin Cash USD',
    'LEO-USD': 'UNUS SED LEO USD',
    'LINK-USD': 'Chainlink USD',
    'FTT-USD': 'FTX Token USD',
    'ATOM-USD': 'Cosmos USD',
    'UNI1-USD': 'Uniswap USD',
    'ALGO-USD': 'Algorand USD',
    'APE3-USD': 'ApeCoin USD',
    'XLM-USD': 'Stellar USD',
    'YOUC-USD': 'yOUcash USD',
    'BTCB-USD': 'Bitcoin BEP2 USD',
    'XMR-USD': 'Monero USD',
    'ETC-USD': 'Ethereum Classic USD',
    'VET-USD': 'VeChain USD',
    'ICP-USD': 'Internet Computer USD',
    'HBAR-USD': 'Hedera USD',
    'FIL-USD': 'Filecoin USD',
    'MANA-USD': 'Decentraland USD',
    'EGLD-USD': 'Elrond USD',
    'FRAX-USD': 'Frax USD',
    'SAND-USD': 'The Sandbox USD',
    'THETA-USD': 'THETA USD',
    'TONCOIN-USD': 'Toncoin USD',
    'XTZ-USD': 'Tezos USD',
    'DFI-USD': 'DeFiChain USD',
    'RUNE-USD': 'THORChain USD',
    'CAKE-USD': 'PancakeSwap USD',
    'EOS-USD': 'EOS USD',
    'WBNB-USD': 'Wrapped BNB USD',
    'AAVE-USD': 'Aave USD',
    'FTM-USD': 'Fantom USD',
    'KLAY-USD': 'Klaytn USD',
    'GMT3-USD': 'Green Metaverse Token USD',
    'BTT-USD': 'BitTorrent USD',
    'AXS-USD': 'Axie Infinity USD',
    'HNT-USD': 'Helium USD',
    'KCS-USD': 'KuCoin Token USD',
    'ZEC-USD': 'Zcash USD',
    'FLOW-USD': 'Flow USD',
    'BTT2-USD': 'BitTorrent (new) USD',
    'WAVES-USD': 'Waves USD',
    'HBTC-USD': 'Huobi BTC USD',
    'GRT1-USD': 'The Graph USD',
    'CVX-USD': 'Convex Finance USD',
    'HT-USD': 'Huobi Token USD',
    'XCN1-USD': 'Chain USD',
    'MIOTA-USD': 'IOTA USD',
    'BSV-USD': 'Bitcoin SV USD',
    'MKR-USD': 'Maker USD',
    'XEC-USD': 'eCash USD',
    'TUSD-USD': 'TrueUSD USD',
    'NEO-USD': 'Neo USD',
    'STX-USD': 'Stacks USD',
    'NEXO-USD': 'Nexo USD',
    'QNT-USD': 'Quant USD',
    'KSM-USD': 'Kusama USD',
    'OSMO-USD': 'Osmosis USD',
    'OKB-USD': 'OKB USD',
    'CRV-USD': 'Curve DAO Token USD',
    'CHZ-USD': 'Chiliz USD',
    'CELO-USD': 'Celo USD',
    'ONE1-USD': 'Harmony USD',
    'GALA-USD': 'Gala USD',
    'LRC-USD': 'Loopring USD',
    'ENJ-USD': 'Enjin Coin USD',
    'DASH-USD': 'Dash USD',
    'USDP-USD': 'Pax Dollar USD',
    'ZIL-USD': 'Zilliqa USD',
    'USDN-USD': 'Neutrino USD USD',
    'BAT-USD': 'Basic Attention Token USD',
    'LDO-USD': 'Lido DAO Token USD',
    'MINA-USD': 'Mina USD',
    'AR-USD': 'Arweave USD',
    'XEM-USD': 'NEM USD',
    'XDC-USD': 'XDC Network USD',
  };

  //TODO fill with data from https://datahub.io/core/s-and-p-500-companies
  static Map<String, String> companies = {
    'FTCH': 'Farfetch',
    'PYPL': 'Paypal',
    'DIS': 'Disney',
    'KO': 'Coke',
    'NFLX': 'Netflix',
    'CRWD': 'Crowdstrike',
    'ETSY': 'Etsy',
    'FVRR': 'Fiverr',
    'ZM': 'Zoom',
    'HPQ': 'HP',
    'GE': 'General Eletric',
    'JPM': 'JP Morgan',
    'CHL': 'China Mobile',
    'TWTR': 'Twitter',
    'ACN': 'Accenture',
    'GS': 'Goldman sachs',
    'AMD': 'Advanced Micro Devices',
    'SHOP': 'Shopify',
    'BRK': 'Berkshire',
    'TSLA': 'Tesla',
    'TSM': 'Taiwan Semiconductors',
    'UNH': 'United Health',
    'FB': 'Facebook',
    'AAPL': 'Apple',
    'XOM': 'Exxon',
    'BAC': 'Bank of America',
    'HSBC': 'HSBC',
    'AMZN': 'Amazon',
    'GOOG': 'Google',
    'MSFT': 'Microsoft',
    'BIDU': 'Baidu',
    'BABA': 'Alibaba',
    'WMT': 'Walmart',
    'JNJ': 'Johnson',
    'PG': 'Procter & gamble',
    'V': 'Visa',
    'NVDA': 'Nvidia',
    'INTC': 'Intel',
    'CROX': 'Crocs',
  };
}
